#!/usr/bin/env bash

# Shared deployment helpers. This file intentionally contains no credentials.

ECR_CONFIG_FILE="${ECR_CONFIG_FILE:-/etc/ecr/deployment.conf}"
ECR_DEFAULT_INSTALL_DIR="/opt/ecr"
ECR_DEFAULT_REPOSITORY_URL="https://github.com/Namir-AI/ECR.git"
ECR_DEFAULT_SERVICE_USER="ecr"
ECR_DEFAULT_SERVICE_NAME="ecr"
ECR_DEFAULT_APP_PORT="8000"
ECR_PRODUCTION_PYTHON_VERSION="3.12"

log() {
    printf '[ECR] %s\n' "$*" >&2
}

warn() {
    printf '[ECR] WARNING: %s\n' "$*" >&2
}

die() {
    printf '[ECR] ERROR: %s\n' "$*" >&2
    exit 1
}

error_report() {
    local exit_code=$?
    local line_number=${1:-unknown}
    printf '[ECR] ERROR: command failed near line %s (exit %s).\n' \
        "$line_number" "$exit_code" >&2
    exit "$exit_code"
}

require_root() {
    [[ ${EUID} -eq 0 ]] || die "Run this command with sudo or as root."
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Required command is unavailable: $1"
}

validate_install_dir() {
    local value=$1
    [[ "$value" =~ ^/[A-Za-z0-9._/-]+$ ]] || \
        die "Installation directory must be an absolute path using letters, digits, ., _, -, and /."
    [[ "$value" != "/" && "$value" != "/opt" ]] || \
        die "Installation directory is too broad."
}

validate_domain() {
    local value=$1
    [[ ${#value} -le 253 ]] || die "Domain is too long."
    [[ "$value" =~ ^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$ ]] || \
        die "Enter a valid DNS hostname without a scheme or path."
}

validate_git_ref() {
    local value=$1
    [[ -n "$value" && "$value" != -* ]] || die "Git ref is invalid."
    [[ "$value" =~ ^[A-Za-z0-9._/-]+$ ]] || die "Git ref contains unsupported characters."
    [[ "$value" != *..* ]] || die "Git ref must not contain '..'."
}

validate_port() {
    local value=$1
    [[ "$value" =~ ^[0-9]+$ ]] || die "Port must be numeric."
    (( value >= 1 && value <= 65535 )) || die "Port must be between 1 and 65535."
}

validate_db_identifier() {
    local label=$1
    local value=$2
    [[ "$value" =~ ^[A-Za-z0-9_]+$ ]] || \
        die "$label may contain only letters, digits, and underscore."
}

validate_repository_url() {
    local value=$1
    case "$value" in
        https://github.com/*/*.git|git@github.com:*/*.git)
            ;;
        *)
            die "Repository URL must be a GitHub HTTPS or SSH .git URL."
            ;;
    esac
    [[ "$value" != https://*@* ]] || \
        die "Credentials must not be embedded in the repository URL."
}

validate_secret_value() {
    local label=$1
    local value=$2
    [[ -n "$value" ]] || die "$label must not be empty."
    [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || \
        die "$label must be a single line."
    [[ "$value" != *'${'* ]] || \
        die "$label must not contain the literal sequence '\${' because dotenv interpolation would alter it."
}

prompt_value() {
    local prompt=$1
    local default=${2:-}
    local value
    if [[ -n "$default" ]]; then
        read -r -p "$prompt [$default]: " value
        printf '%s' "${value:-$default}"
    else
        read -r -p "$prompt: " value
        printf '%s' "$value"
    fi
}

prompt_secret() {
    local prompt=$1
    local value
    read -r -s -p "$prompt: " value
    printf '\n' >&2
    printf '%s' "$value"
}

confirm() {
    local prompt=$1
    local default=${2:-Y}
    local answer
    if [[ "$default" == "Y" ]]; then
        read -r -p "$prompt [Y/n]: " answer
        answer=${answer:-Y}
    else
        read -r -p "$prompt [y/N]: " answer
        answer=${answer:-N}
    fi
    [[ "$answer" =~ ^[Yy]$ ]]
}

load_deployment_config() {
    [[ -r "$ECR_CONFIG_FILE" ]] || die "Deployment configuration not found: $ECR_CONFIG_FILE"
    # This file is root-owned, contains no secrets, and is generated by install.sh.
    # shellcheck disable=SC1090
    source "$ECR_CONFIG_FILE"
    : "${ECR_INSTALL_DIR:?Missing ECR_INSTALL_DIR}"
    : "${ECR_DOMAIN:?Missing ECR_DOMAIN}"
    : "${ECR_SERVICE_USER:?Missing ECR_SERVICE_USER}"
    : "${ECR_SERVICE_NAME:?Missing ECR_SERVICE_NAME}"
    : "${ECR_APP_PORT:?Missing ECR_APP_PORT}"
}

acquire_deployment_lock() {
    local lock_file=${1:-/run/lock/ecr-deployment.lock}
    exec 9>"$lock_file"
    flock -n 9 || die "Another ECR deployment operation is already running."
}

run_as_service() {
    runuser -u "$ECR_SERVICE_USER" -- "$@"
}

git_as_deployer() {
    local ssh_command=""
    if [[ -n "${ECR_DEPLOY_KEY_FILE:-}" ]]; then
        [[ -r "$ECR_DEPLOY_KEY_FILE" ]] || \
            die "Configured GitHub Deploy Key is not readable: $ECR_DEPLOY_KEY_FILE"
        ssh_command="ssh -i $ECR_DEPLOY_KEY_FILE -o IdentitiesOnly=yes -o UserKnownHostsFile=/etc/ecr/github_known_hosts"
    fi

    if [[ -n "$ssh_command" ]]; then
        env GIT_SSH_COMMAND="$ssh_command" git "$@"
    else
        git "$@"
    fi
}

ensure_install_layout() {
    install -d -o root -g "$ECR_SERVICE_USER" -m 0750 "$ECR_INSTALL_DIR"
    install -d -o root -g root -m 0755 \
        "$ECR_INSTALL_DIR/releases"
    install -d -o root -g "$ECR_SERVICE_USER" -m 0750 \
        "$ECR_INSTALL_DIR/shared"
    install -d -o "$ECR_SERVICE_USER" -g "$ECR_SERVICE_USER" -m 0750 \
        "$ECR_INSTALL_DIR/shared/data" \
        "$ECR_INSTALL_DIR/shared/logs"
    install -d -o root -g root -m 0750 \
        "$ECR_INSTALL_DIR/shared/uv-cache"
    install -d -o root -g "$ECR_SERVICE_USER" -m 0750 \
        "$ECR_INSTALL_DIR/shared/uv-python"
    install -d -o root -g "$ECR_SERVICE_USER" -m 0750 \
        "$ECR_INSTALL_DIR/state" "$ECR_INSTALL_DIR/backups"
}

ensure_production_python() {
    require_command uv
    local python_install_dir="$ECR_INSTALL_DIR/shared/uv-python"
    local python_path

    install -d -o root -g "$ECR_SERVICE_USER" -m 0750 "$python_install_dir"
    log "Ensuring uv-managed CPython $ECR_PRODUCTION_PYTHON_VERSION is available."
    env -u VIRTUAL_ENV \
        UV_CACHE_DIR="$ECR_INSTALL_DIR/shared/uv-cache" \
        UV_PYTHON_INSTALL_DIR="$python_install_dir" \
        uv python install --no-bin "$ECR_PRODUCTION_PYTHON_VERSION"

    python_path=$(env -u VIRTUAL_ENV \
        UV_CACHE_DIR="$ECR_INSTALL_DIR/shared/uv-cache" \
        UV_PYTHON_INSTALL_DIR="$python_install_dir" \
        uv python find --no-project --managed-python \
            "$ECR_PRODUCTION_PYTHON_VERSION")
    [[ -x "$python_path" ]] || die "uv-managed Python is unavailable after installation."
    case "$python_path" in
        "$python_install_dir"/*) ;;
        *) die "uv resolved Python outside the protected production runtime directory." ;;
    esac
    "$python_path" -c 'import sys; assert sys.version_info[:2] == (3, 12)'
    ECR_PRODUCTION_PYTHON=$python_path
}

sync_release_dependencies() {
    local release_dir=$1
    ensure_production_python
    env -u VIRTUAL_ENV \
        UV_CACHE_DIR="$ECR_INSTALL_DIR/shared/uv-cache" \
        UV_PYTHON_INSTALL_DIR="$ECR_INSTALL_DIR/shared/uv-python" \
        uv sync --directory "$release_dir" --frozen --no-dev \
            --python "$ECR_PRODUCTION_PYTHON" --managed-python --no-python-downloads
}

ensure_repository() {
    local repository_dir="$ECR_INSTALL_DIR/repository.git"
    if [[ ( -e "$repository_dir" || -L "$repository_dir" ) && \
            ! -f "$repository_dir/HEAD" ]]; then
        if [[ ${INSTALL_MODE:-} == "recover" || \
                ${INSTALL_MODE:-} == "recover-reconfigure" ]]; then
            local quarantined_repository
            quarantined_repository="${repository_dir}.incomplete.$(date -u +%Y%m%dT%H%M%SZ).$$"
            warn "Quarantining an incomplete deployment repository mirror."
            mv -- "$repository_dir" "$quarantined_repository"
        else
            die "Repository mirror is invalid: $repository_dir"
        fi
    fi
    if [[ ! -d "$repository_dir" ]]; then
        log "Cloning deployment repository mirror."
        git_as_deployer clone --mirror "$ECR_REPOSITORY_URL" "$repository_dir"
    else
        [[ -f "$repository_dir/HEAD" ]] || die "Repository mirror is invalid: $repository_dir"
        local current_origin
        current_origin=$(git_as_deployer --git-dir="$repository_dir" remote get-url origin)
        if [[ "$current_origin" != "$ECR_REPOSITORY_URL" ]]; then
            if [[ ${ECR_ALLOW_REPOSITORY_RECONFIGURE:-false} == "true" ]]; then
                log "Updating the deployment mirror origin after explicit reconfiguration."
                git_as_deployer --git-dir="$repository_dir" remote set-url origin \
                    "$ECR_REPOSITORY_URL"
            else
                die "Existing repository origin differs from deployment configuration. Use installer reconfiguration."
            fi
        fi
    fi
}

fetch_repository() {
    local repository_dir="$ECR_INSTALL_DIR/repository.git"
    log "Fetching branches and tags from GitHub."
    git_as_deployer --git-dir="$repository_dir" fetch --prune origin \
        '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
}

resolve_git_ref() {
    local requested_ref=$1
    local repository_dir="$ECR_INSTALL_DIR/repository.git"
    local candidate
    for candidate in \
        "$requested_ref^{commit}" \
        "refs/heads/$requested_ref^{commit}" \
        "refs/tags/$requested_ref^{commit}"; do
        if git_as_deployer --git-dir="$repository_dir" rev-parse --verify --quiet "$candidate"; then
            return 0
        fi
    done
    return 1
}

prepare_release() {
    local commit=$1
    local timestamp short_commit release_dir
    {
        timestamp=$(date -u +%Y%m%dT%H%M%SZ)
        short_commit=${commit:0:12}
        release_dir="$ECR_INSTALL_DIR/releases/${timestamp}-${short_commit}"
        [[ ! -e "$release_dir" ]] || die "Release path already exists: $release_dir"

        log "Preparing isolated application release $short_commit."
        git_as_deployer --git-dir="$ECR_INSTALL_DIR/repository.git" \
            worktree add --detach "$release_dir" "$commit"
        local required_file
        for required_file in \
            pyproject.toml uv.lock app/main.py alembic.ini \
            install/update.sh install/status.sh install/lib/env_tools.py; do
            [[ -f "$release_dir/$required_file" ]] || \
                die "Requested ref lacks required deployment/application file: $required_file"
        done
        if [[ -f "$ECR_INSTALL_DIR/shared/.env" ]]; then
            ln -s "$ECR_INSTALL_DIR/shared/.env" "$release_dir/.env"
        fi
        sync_release_dependencies "$release_dir"
    } >&2

    # stdout is the function's return channel for command substitution.
    printf '%s\n' "$release_dir"
}

link_release_env() {
    local release_dir=$1
    [[ -f "$ECR_INSTALL_DIR/shared/.env" ]] || die "Production .env is missing."
    if [[ ! -L "$release_dir/.env" ]]; then
        [[ ! -e "$release_dir/.env" ]] || die "Release contains an unexpected .env file."
        ln -s "$ECR_INSTALL_DIR/shared/.env" "$release_dir/.env"
    fi
}

activate_release() {
    local release_dir=$1
    local temporary_link="$ECR_INSTALL_DIR/.current.$$.tmp"
    ln -s "$release_dir" "$temporary_link"
    mv -Tf "$temporary_link" "$ECR_INSTALL_DIR/current"
}

run_db_check() {
    local release_dir=$1
    (cd "$release_dir" && run_as_service "$release_dir/.venv/bin/python" -m app.db.check)
}

run_migrations() {
    local release_dir=$1
    (cd "$release_dir" && run_as_service "$release_dir/.venv/bin/alembic" upgrade head)
}

local_health_check() {
    local port=${ECR_APP_PORT:-8000}
    curl -fsS --max-time 15 "http://127.0.0.1:${port}/health" | \
        grep -Eq '"status"[[:space:]]*:[[:space:]]*"ok"'
}

https_health_check() {
    curl -fsS --max-time 20 --resolve "${ECR_DOMAIN}:443:127.0.0.1" \
        "https://${ECR_DOMAIN}/health" | \
        grep -Eq '"status"[[:space:]]*:[[:space:]]*"ok"'
}

wait_for_local_health() {
    local attempts=${1:-30}
    local count
    for ((count = 1; count <= attempts; count++)); do
        if local_health_check; then
            return 0
        fi
        sleep 1
    done
    return 1
}

write_deployment_state() {
    local current_commit=$1
    local current_ref=$2
    local previous_release=${3:-}
    local state_file="$ECR_INSTALL_DIR/state/deployment.env"
    local temporary_file
    temporary_file=$(mktemp "$ECR_INSTALL_DIR/state/deployment.env.XXXXXX")
    {
        printf 'ECR_CURRENT_COMMIT=%q\n' "$current_commit"
        printf 'ECR_CURRENT_REF=%q\n' "$current_ref"
        printf 'ECR_PREVIOUS_RELEASE=%q\n' "$previous_release"
        printf 'ECR_DEPLOYED_AT=%q\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    } >"$temporary_file"
    chown root:"$ECR_SERVICE_USER" "$temporary_file"
    chmod 0640 "$temporary_file"
    mv -f "$temporary_file" "$state_file"
}

append_deployment_history() {
    local action=$1
    local ref=$2
    local commit=$3
    local release_dir=$4
    local history_file="$ECR_INSTALL_DIR/state/deployment-history.tsv"
    printf '%s\t%s\t%s\t%s\t%s\n' \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$action" "$ref" "$commit" "$release_dir" \
        >>"$history_file"
    chown root:"$ECR_SERVICE_USER" "$history_file"
    chmod 0640 "$history_file"
}

load_deployment_state() {
    local state_file="$ECR_INSTALL_DIR/state/deployment.env"
    [[ -r "$state_file" ]] || return 1
    # Root-owned deployment metadata, generated by this toolset.
    # shellcheck disable=SC1090
    source "$state_file"
}

current_release_path() {
    [[ -L "$ECR_INSTALL_DIR/current" ]] || return 1
    readlink -f "$ECR_INSTALL_DIR/current"
}

valid_current_release_path() {
    local release_dir
    release_dir=$(current_release_path) || return 1
    [[ -d "$release_dir" ]] || return 1
    [[ -x "$release_dir/.venv/bin/python" ]] || return 1
    [[ -f "$release_dir/app/main.py" ]] || return 1
    [[ -f "$release_dir/install/status.sh" ]] || return 1
    printf '%s\n' "$release_dir"
}

read_database_environment_from_release() {
    local release_dir=$1
    local helper="$release_dir/install/lib/env_tools.py"
    local python="$release_dir/.venv/bin/python"
    [[ -x "$python" && -f "$helper" ]] || die "Deployment environment reader is unavailable."
    local -a values=()
    mapfile -d '' -t values < <(
        "$python" "$helper" read "$ECR_INSTALL_DIR/shared/.env" \
            DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD
    )
    (( ${#values[@]} == 5 )) || die "Production database configuration is incomplete."
    ECR_DB_HOST_VALUE=${values[0]}
    ECR_DB_PORT_VALUE=${values[1]}
    ECR_DB_NAME_VALUE=${values[2]}
    ECR_DB_USER_VALUE=${values[3]}
    ECR_DB_PASSWORD_VALUE=${values[4]}
}

read_database_environment() {
    local release_dir
    release_dir=$(valid_current_release_path) || die "Current application release is unavailable."
    read_database_environment_from_release "$release_dir"
}

safe_backup_path() {
    local candidate=$1
    local resolved backup_root
    backup_root=$(readlink -f "$ECR_INSTALL_DIR/backups")
    resolved=$(readlink -f "$candidate") || return 1
    [[ "$resolved" == "$backup_root"/*.sql.gz ]] || return 1
    printf '%s\n' "$resolved"
}
