#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=install/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
trap 'error_report "$LINENO"' ERR

require_root
load_deployment_config
acquire_deployment_lock
require_command mysql
require_command gzip
require_command sha256sum
read_database_environment

if [[ $# -gt 1 ]]; then
    die "Usage: $0 [BACKUP.sql.gz]"
fi

if [[ $# -eq 0 ]]; then
    log "Available SQL backups:"
    find "$ECR_INSTALL_DIR/backups" -maxdepth 1 -type f -name 'ecr-*.sql.gz' \
        -printf '  %f\n' | sort -r
    read -r -p "Backup filename to restore: " requested_backup
    requested_backup="$ECR_INSTALL_DIR/backups/$requested_backup"
else
    requested_backup=$1
    [[ "$requested_backup" == /* ]] || requested_backup="$PWD/$requested_backup"
fi

backup_file=$(safe_backup_path "$requested_backup") || \
    die "Backup must be a .sql.gz file inside $ECR_INSTALL_DIR/backups."
metadata_file=${backup_file%.sql.gz}.meta
backup_timestamp="unknown"
backup_database="unknown"
expected_checksum=""
if [[ -r "$metadata_file" ]]; then
    # Metadata is generated by backup.sh and contains no secrets.
    # shellcheck disable=SC1090
    source "$metadata_file"
    backup_timestamp=${BACKUP_TIMESTAMP:-unknown}
    backup_database=${DATABASE_NAME:-unknown}
    expected_checksum=${SQL_SHA256:-}
fi

gzip -t "$backup_file" || die "Backup gzip validation failed."
if [[ -n "$expected_checksum" ]]; then
    actual_checksum=$(sha256sum "$backup_file" | awk '{print $1}')
    [[ "$actual_checksum" == "$expected_checksum" ]] || die "Backup checksum validation failed."
fi

printf 'Restore target database : %s\n' "$ECR_DB_NAME_VALUE"
printf 'Restore target host     : %s\n' "$ECR_DB_HOST_VALUE"
printf 'Backup file             : %s\n' "$backup_file"
printf 'Backup timestamp        : %s\n' "$backup_timestamp"
printf 'Backup database         : %s\n' "$backup_database"
printf 'Application code and Alembic are NOT rolled back by this operation.\n'
read -r -p "Type RESTORE ${ECR_DB_NAME_VALUE} to continue: " confirmation
[[ "$confirmation" == "RESTORE ${ECR_DB_NAME_VALUE}" ]] || die "Restore cancelled."

log "Creating a safety backup before restore."
"$SCRIPT_DIR/backup.sh" >/dev/null

service_was_active=false
if systemctl is-active --quiet "$ECR_SERVICE_NAME.service"; then
    service_was_active=true
    systemctl stop "$ECR_SERVICE_NAME.service"
fi

restart_service() {
    if [[ "$service_was_active" == true ]]; then
        systemctl start "$ECR_SERVICE_NAME.service" || true
    fi
}
trap restart_service EXIT

log "Restoring selected database backup."
gzip -dc "$backup_file" | env MYSQL_PWD="$ECR_DB_PASSWORD_VALUE" mysql \
    --host="$ECR_DB_HOST_VALUE" \
    --port="$ECR_DB_PORT_VALUE" \
    --user="$ECR_DB_USER_VALUE" \
    --protocol=TCP \
    --database="$ECR_DB_NAME_VALUE"

current_release=$(current_release_path)
run_db_check "$current_release"
if [[ "$service_was_active" == true ]]; then
    systemctl start "$ECR_SERVICE_NAME.service"
    wait_for_local_health 30 || die "Database restored, but application health check failed."
fi
trap - EXIT
log "Restore completed. Verify application/schema compatibility with the backup metadata."
